import mongoose from "mongoose";

// Admin-facing notifications, generated by cron jobs and live events
// (new seller registration, low stock, large orders, refund requests...).
const notificationSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      enum: [
        "new_seller",
        "new_product",
        "low_stock",
        "large_order",
        "refund_request",
        "pending_seller_overdue",
        "announcement",
        "new_review",
        "seller_reply",
        "review_approved",
        "review_deleted",
        "reported_review",
        "spam_detected",
        "review_reminder",
      ],
      required: true,
    },
    title: { type: String, required: true, trim: true },
    message: { type: String, required: true, trim: true },
    relatedId: { type: mongoose.Schema.Types.ObjectId, default: null },
    relatedModel: { type: String, default: null },
    isRead: { type: Boolean, default: false },
  },
  { timestamps: true }
);

notificationSchema.index({ isRead: 1, createdAt: -1 });

const Notification = mongoose.model("Notification", notificationSchema);
export default Notification;
